name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install cppcheck
      run: sudo apt-get update && sudo apt-get -y install cppcheck

    - name : install norminette
      run: python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette

    - name: Build
      run: make

    - name: Run check
      run: make check

    - name: Run tests
      run: make test
